// 站内视频目录(供 AI 推荐使用)
export const VIDEO_CATALOG = [
  { id: "v1", movement: "深蹲", title: "普通人如何学会一个标准的深蹲？【卓叔】" },
  { id: "v2", movement: "深蹲", title: "【优形志】7分钟深蹲跟练，入门到进阶详解，标准深蹲，" },
  { id: "v3", movement: "卧推", title: "练胸教程：杠铃卧推的动作 模式、常见错误、发力技巧" },
  { id: "v4", movement: "卧推", title: "练胸王牌动作讲解｜饱满胸肌必备｜杠铃卧推 (详细教程" },
  { id: "v5", movement: "硬拉", title: "硬拉标准动作教学 (中文字幕)" },
  { id: "v6", movement: "硬拉", title: "健身动作指南｜8分钟学会硬拉 (保姆级讲解)" },
  { id: "v7", movement: "俯卧撑", title: "【从0到1】如何做一个标准的俯卧撑! (并提高数量)" },
  { id: "v8", movement: "引体向上", title: "如何快速提升引体向上数量？从0到10+！" },
  { id: "v9", movement: "哑铃训练", title: "一对哑铃练完全身，哑铃居家全身分化训练计划，哑铃全身" },
  { id: "v10", movement: "杠铃训练", title: "全套杠铃训练动作，杠铃全身训练攻略，教你明明白白练全" },
  { id: "v11", movement: "肩部训练", title: "拯救窄肩，告别瘦弱体型!(无器械练肩)" },
  { id: "v12", movement: "背部训练", title: "新系列来喽，保姆级私教视角之背部训练！！希望对大家有" },
  { id: "v13", movement: "手臂训练", title: "【中字】帕梅拉10分钟紧实手臂训练，在家用水壶就能瘦" },
  { id: "v14", movement: "臀部训练", title: "10分钟臀部燃烧 | 无脑跟着练无需器械 | Pam" },
  { id: "v15", movement: "全身有氧操", title: "30分钟全程站立有氧燃脂操｜无跳跃 无深蹲 膝友好【" },
  { id: "v16", movement: "燃脂操", title: "【谁跳谁瘦！】30分钟有氧燃脂舞合集｜零基础/暴汗/" },
  { id: "v17", movement: "全身有氧", title: "【Pamela Reif 帕梅拉】20分钟全身有氧 " },
  { id: "v18", movement: "全身燃脂", title: "Pamela Reif10mins全身燃脂训练，瘦全" },
  { id: "v19", movement: "瑜伽入门", title: "【50分钟初学者入门瑜伽】一套完整的基础瑜伽练习 5" },
  { id: "v20", movement: "流瑜伽", title: "【60分钟流瑜伽】改善紧绷僵硬 疏通关节气血 增强全" },
  { id: "v21", movement: "流瑜伽", title: "【60分钟减脂流瑜伽】全身燃脂，改善体力，同时增强核" },
  { id: "v22", movement: "阴瑜伽", title: "10分钟睡前阴瑜伽跟练疏通肝经，排毒养肤" },
  { id: "v23", movement: "阴瑜伽", title: "30min 阴瑜伽|平衡全身经络 拉伸放松 零基础居" },
  { id: "v24", movement: "睡前瑜伽", title: "睡前瑜伽跟练14min｜加速胃排空，缓解身体疲劳肿胀" },
  { id: "v25", movement: "哈他瑜伽", title: "【60分钟哈他瑜伽入门和提升】稳定根基，提升全身力量" },
  { id: "v26", movement: "腹部瑜伽", title: "帕梅拉 - 10min 腹部+瑜伽训练 慢速放松高效" },
  { id: "v27", movement: "HIIT燃脂", title: "帕梅拉 - 10分钟HIIT燃脂！高强全身燃脂训练 " },
  { id: "v28", movement: "HIIT燃脂", title: "20min全身燃脂增肌无器械HIIT训练【克里斯健身" },
  { id: "v29", movement: "Tabata", title: "火辣健身-减脂集中营-Tabata高级训练-难度L4" },
  { id: "v30", movement: "波比跳", title: "世界最强燃脂动作—波比跳保姆级教学！" },
  { id: "v31", movement: "波比跳", title: "30分钟波比跳燃脂挑战HIIT训练" },
  { id: "v32", movement: "全身拉伸", title: "20分钟久坐全身拉伸｜舒缓疼痛、改善体态、提升睡眠质" },
  { id: "v33", movement: "全身拉伸", title: "自用，跑步，骑行运动后全身拉伸，全程站立，舒展筋骨，" },
  { id: "v34", movement: "腿部拉伸", title: "帕梅拉 - 9min 臀+腿拉伸-拉长腿部线条 塑形" },
  { id: "v35", movement: "腿部拉伸", title: "腿部拉伸 | 改善肌肉型腿粗·get细长直美腿！" },
  { id: "v36", movement: "背部拉伸", title: "【Mady Morrison】久坐压力缓解！10分钟" },
  { id: "v37", movement: "跑后拉伸", title: "体大硕士带你正确拉伸｜跑前动态拉伸+跑后深度拉伸+入" },
  { id: "v38", movement: "每日拉伸", title: "帕梅拉 - 5min 每日拉伸 - 运动后|睡前|清" },
  { id: "v39", movement: "普拉提塑形", title: "零基础 30min普拉提塑形|详细口令版" },
  { id: "v40", movement: "普拉提塑形", title: "帕梅拉 - 15分钟普拉提训练|慢速全身紧实 膝盖友" },
  { id: "v41", movement: "普拉提核心", title: "【Eleni Fit】30分钟普拉提总核心／腹肌锻炼" },
  { id: "v42", movement: "普拉提瘦腿", title: "【虐腿】高强度瘦腿|普拉提100次大腿外侧＋100次" },
  { id: "v43", movement: "全身普拉提", title: "【Rita Mark】30分钟全身普拉提" },
  { id: "v44", movement: "燃脂舞", title: "街角的晚风燃脂舞跟练！太上瘾了！" },
  { id: "v45", movement: "尊巴舞", title: "快乐燃脂！30分钟有氧尊巴舞蹈操，无跳跃膝盖友好！（" },
  { id: "v46", movement: "健身操舞", title: "7分钟超长版大众零基础健身操，强力燃脂减肥操《我不是" },
  { id: "v47", movement: "欢乐燃脂", title: "帕梅拉 莱孚 12min Happy Sweat W" },
  { id: "v48", movement: "搏击操", title: "30分钟轻松掉肉全身塑形！ 燃脂搏击操 (基础公测篇" },
  { id: "v49", movement: "拳击基础", title: "【超完整0基础拳击教程】：所有人都该观看收藏的“拳击" },
  { id: "v50", movement: "泰拳", title: "五分钟跟练｜泰拳，新手友好" },
  { id: "v51", movement: "泰拳", title: "泰国TC泰拳学院基础线上教练课程" },
  { id: "v52", movement: "跑步姿势", title: "【收藏向】不懂这些，跑步受伤粗腿是迟早的事｜保姆级跑" },
  { id: "v53", movement: "跑步姿势", title: "【反直觉】为什么跑快反而轻松？世界顶级跑步教练的跑姿" },
  { id: "v54", movement: "跑步入门", title: "6个方法，入门跑步更轻松｜新手福音" },
  { id: "v55", movement: "跑鞋选择", title: "7 款入门跑鞋推荐，手把手教你，跑步新手如何选鞋【子" },
  { id: "v56", movement: "间歇跑", title: "三种老少皆宜的间歇跑训练方法！ 间歇跑管用，但练错了" },
  { id: "v57", movement: "间歇跑", title: "间歇怎么跑？" },
  { id: "v58", movement: "动感单车", title: "动感单车燃脂训练，坚持骑行20天，轻松瘦出马甲线" },
  { id: "v59", movement: "动感单车", title: "动感单车30分钟超级燃脂骑行课程！新手友好！欢乐瘦身" },
  { id: "v60", movement: "骑行技巧", title: "新手骑行教学：如何变速、如何加减档、什么路段搭配什么" },
  { id: "v61", movement: "自由泳", title: "【合集】自由泳入门（第二版）｜梦觉教游泳" },
  { id: "v62", movement: "自由泳", title: "20分钟长视频，给到想学自由泳的朋友一个系统教学步骤" },
  { id: "v63", movement: "蛙泳", title: "详细版蛙泳教学，跟我一起练起来，可以给你省去几千块！" },
  { id: "v64", movement: "蛙泳", title: "零基础教你6步学会蛙泳" },
  { id: "v65", movement: "仰泳", title: "【合集】仰泳入门｜梦觉教游泳" },
  { id: "v66", movement: "仰泳", title: "5步教你学会仰泳" },
  { id: "v67", movement: "跳绳入门", title: "零基础跳绳教学" },
  { id: "v68", movement: "花式跳绳", title: "怎样跳绳最有趣？学会这24个花式跳绳动作，跳绳乐趣增" },
  { id: "v69", movement: "跳绳燃脂", title: "25分钟刷脂跳绳！全程卡点超燃脂🔥" },
  { id: "v70", movement: "跳绳燃脂", title: "15分钟刷脂跳绳跟练🔥全程卡点超燃脂" },
  { id: "v71", movement: "攀岩入门", title: "【攀岩教学】室内攀岩科普基础入门视频教程，体验岩壁上" },
  { id: "v72", movement: "抱石技巧", title: "5个抱石原则！帮助新手快速进步" },
  { id: "v73", movement: "抱石训练", title: "攀岩|教学Adam Ondra教你怎么高效抱石训练，" },
  { id: "v74", movement: "徒步入门", title: "新手如何开启第一次徒步，初级攻略全分享，户外徒步纯干" },
  { id: "v75", movement: "徒步路线", title: "新手徒步系列|路线选择、路线评估和装备入门！" },
  { id: "v76", movement: "徒步装备", title: "徒步小白必看｜户外徒步装备如何选择｜干货！" },
  { id: "v77", movement: "户外装备", title: "新手如何选择户外装备，购买户外装备建议，登山装备、露" },
  { id: "v78", movement: "腹肌训练", title: "【Pamela Reif 帕梅拉】10分钟腹部训练 " },
  { id: "v79", movement: "腹肌训练", title: "三十天练出腹肌（跟练版）｜噩梦级" },
  { id: "v80", movement: "平板支撑", title: "掌握平板支撑正确做法，轻松突破1分钟" },
  { id: "v81", movement: "平板支撑", title: "你真的做对平板支撑了吗？（保姆级教学）" },
  { id: "v82", movement: "卷腹", title: "干货|如何做一个标准的卷腹？找到腹肌发力感，不伤脖子" },
  { id: "v83", movement: "卷腹", title: "打造立体腹肌，告别小肚腩｜卷腹这么做！" },
  { id: "v84", movement: "新手腹肌", title: "魔鬼帕梅拉10分钟减腹瘦腰，针对新手，六块腹肌并不难" },
  { id: "v85", movement: "肩颈放松", title: "10分钟有效缓解肩颈酸痛僵硬 每天一遍告别不良体态 " },
  { id: "v86", movement: "肩颈瑜伽", title: "【10分钟肩颈放松瑜伽】办公族学生党自救拉伸！原地快" },
  { id: "v87", movement: "髋关节灵活", title: "髋关节灵活度训练 10分钟完整版" },
  { id: "v88", movement: "体态矫正", title: "帕梅拉 - 10分钟拜拜圆肩驼背｜拉伸训练 改善不良" },
  { id: "v89", movement: "泡沫轴放松", title: "9分钟跟练版泡沫轴放松肩背，缓解后背僵硬，改善不良体" },
  { id: "v90", movement: "泡沫轴放松", title: "【自用】韩小四泡沫轴腿部放松" },
];
